# System Info and memory mappings
MainSettings:

  # path to the binary
  bin_path      : "./demos/mipsel/demo"

  # options: ARM      M68K     MIPS     RISCV    SPARC    X86
  #          ARM64    MAX      PPC      S390X    TRICORE
  architecture  : MIPS

  # options: 32, 64
  bit           : 32

  # options: BIG, LITTLE
  endian        : LITTLE

  # where the binary is loaded into memory
  text_address  : 0x10000

  # address to being the emulation at
  start_address : 0x00010720
  end_address   : 0x00010770

  # ------ OPTIONAL ARGUMENTS BELOW ---- 

  # memory address must be page aligned -> 0x1000 
  # Numerical low value of the bss segment
  bss_low       : ~
  bss_high      : ~

  stack_low     : ~
  stack_high    : ~ 

# document 2 - Function Arguments
FunctionArgs    :  
  - 
    # OPTIONS: pointer, literal
    type        : pointer
    size        : 4
    value       : 8
  - 
    # OPTIONS: pointer, literal
    type        : literal
    size        : ~
    value       : 3


# document 3 - Global variables assignments
GlobalVariables: ~

